# Generated by Django 3.1.1 on 2020-09-20 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_vis', '0002_auto_20200920_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdffile',
            old_name='imported',
            new_name='is_imported',
        ),
    ]
