# Generated by Django 3.1.1 on 2020-09-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_vis', '0003_auto_20200920_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='meta',
            field=models.TextField(default=''),
        ),
        migrations.AlterUniqueTogether(
            name='datapoint',
            unique_together={('series', 'x', 'dy')},
        ),
    ]
