# Generated by Django 3.1.1 on 2020-09-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_vis', '0004_auto_20200921_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='initial_value',
            field=models.FloatField(default=0),
        ),
    ]
