# Generated by Django 3.1.1 on 2020-09-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_vis', '0006_auto_20200922_0741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='datapoint',
            name='tags',
            field=models.ManyToManyField(related_name='data_points', to='data_vis.Tag'),
        ),
    ]
