# Generated by Django 3.1.1 on 2020-09-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_vis', '0007_auto_20200925_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='meta',
            field=models.TextField(default=''),
        ),
    ]
