# Generated by Django 3.1.1 on 2020-09-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_vis', '0008_tag_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tag',
            name='meta',
            field=models.TextField(blank=True, default=''),
        ),
    ]
